In [2]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [3]:
x = np.arange(1,5,dtype = np.int64)
print(x)

[1 2 3 4]


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.asmatrix(x)
print(y)

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
x = np.linspace(3,10,50,retstep = True)
print(x)

(array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ]), 0.14285714285714285)


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
x = np.dstack((x[0],x[1]))
x = x.reshape(-1)
print(x)


[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x  = np.arange(1,10)
x = np.split(x,[4,6])
print(x)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x  = np.array([[1,2],[3,4]])
np.asmatrix(x)
y = x.trace()
z = np.linalg.inv(x)
print(y)
print(z)


5
[[-2.   1. ]
 [ 1.5 -0.5]]


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
x = np.array([[1,4],[3,1]])
x = np.sort(x,axis = 1)
print(x)



[[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
x = np.array([[1,4],[3,1]])
y = np.argsort(x,axis = 1)
print(y)


[[0 1]
 [1 0]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.random((2,5))
xmax = x.max()
xmin = x.min()
print(x)
print(xmax,xmin)

[[0.00848582 0.16438185 0.92148296 0.80187362 0.83565929]
 [0.90628425 0.40573662 0.2345706  0.13840673 0.15131718]]
0.9214829599066471 0.008485821920979575


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value. 

In [ ]:
row = iris_2d[~np.isnan(iris_2d).any(axis = 1)]


Find the correlation between first two columns.

In [ ]:
col1 = iris_2d[:,1]
col2 = iris_2d[:,2]
print(np.corrcoef(col1,col2))

[[ 1.        -0.4205161]
 [-0.4205161  1.       ]]


Find the mean,median and standard deviation of column 3.

In [ ]:
col3 = iris_2d[:,3]
print(np.mean(col3))
print(np.median(col3))
print(np.std(col3))

1.1986666666666668
1.3
0.7606126185881716


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [ ]:
y = np.unique(names)
print(len(y))

5


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

Find the most frequent value of petal length (3rd column) in iris dataset